#!/usr/bin/env bash
# FizzBuzz
for ((i = 1; i < 101; i++))
do
  	if ((i % 3 == 0 && i % 5 == 0))
  	then
    	result="FizzBuzz"
	elif ((i % 3 == 0))
	then
    	result="Fizz"
	elif ((i % 5 == 0))
	then
    	result="Buzz"
	else
		((result = "$i"))
	fi
	echo $result
done