#!/usr/bin/env bash
# Displays numbers from 1 to 20 with bad luck
i=1
while ((i < 21))
do
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			echo $i
			;;
	esac
	((i++))
done